### PR TITLE
[WIP] Add offline mode detection

### LINKED ISSUE #19: make it so it works without the network (if images are there). (offline mode)
right now cattlepi needs network connectivity when it boots. 
make it so, that if the device previously booted and has a config + correct images cached locally it uses those in the case of no network connectivity. 
this way, the device could be provisioned w/ cattlepi and after that it could also work offline

### PR DESCRIPTION
**Pull request by zmrow**
This should fix #19 

Rather than panicking when we're unable to real the API, continue on and ensure that the corect files/images exist and are readable.

### CODE REVIEW

**Comment by zmrow** [comment]
Just getting this started.

Testing to follow!

**Comment by mirceal** [comment]
Good start. Can you please add [WIP] as a prefix to the PR name so that it’s clear it’s not ready to be merged / brutally reviewed yet? :)

One comment I had was: there is more than one type of offline. One is where you cannot reach the API (like here). Another one is where you don’t have network connectivity. 
2nd one could be problematic (probe for network, time sync, name resolution being a few problems that we may face).

**Comment by zmrow** [comment]
Thanks for changing the title!

Indeed - I'll make those additions as well.

**Comment by zmrow** [comment]
Added offline mode determination to the time adjustment func.

I'll search for more areas that offline mode is necessary.  If you have any locations that need this functionality off the top of your head, I'll gladly implement there as well.

**Comment by mirceal** [comment]
up until now looks okay-ish
may I suggest we check if it's offline just one in the begging and set a flag var that we can use to make decisions throughout the boot process?

**Comment by zmrow** [comment]
Yes, that seems like a much better implementation.

Is there a set entrypoint here though?  Still not super familiar with the entire codebase.

**Comment by zmrow** [comment]
That's a wonderful explanation - MUCH clearer now.  Thanks!

With that info, it shouldn't take much to fix what I've got and get this out.

**Comment by mirceal** [comment]
yup. probably in **netup** script and/or in a prereq, set the flag and after that use it everywhere else.

**Comment by zmrow** [comment]
I read through the Debian docs I’m not seeing anything about shared variables,etc. 

How am I able to set a flag in netup and use it in another script?

**Comment by mirceal** [comment]
the easiest way would be to add a function to the helpers that 
1) checks the presence of a file (put it somewhere in /run?). if file is there it loads the value from file
2) if file is not there, it checks network connectivity and writes the file. 
Invoke the said function and get the value of the network connectivity without checking it each time. you can also check if invoked and don't invoke it again as most things in the helpers file do.

**Comment by zmrow** [comment]
Ah ok, that makes sense. Just thought that perhaps I wasn’t aware of some but of functionality built into these initramfs scripts. 

Now I see there’s no magic, just shell scripts. (Which also makes me happy) 👌

**Comment by mirceal** [comment]
Why do you need to invoke find_params? 

High level, the idea behind ajusting the time is to give the pi the right time and to allow cert validation for ssl to work. 

I would check if the network interface is up in determining if ofline. After that in find params i would try to load the params from the config file if cached

**Comment by zmrow** [comment]
Ok - this should do it.  Rather than check if the interface is up, I'm checking connectivity with the API.  I'm doing this because even if the interface is up or we have network, if we can't get to the API we can't do quite a few early configuration things in this recipe.

So we check for API connectivity and set the flag first.  Using this flag we can determine if we are able to run without connectivity to the API.  Mainly we need a valid config and an image that is valid.  If we determine this to be true, we set the `OFFLINE_MODE` flag to be `true`.

I split these functions out just in case we'd like to use them separately in the future.  I believe I've captured all the comments here.  Will give this some testing and merge provided a ShipIt!

**Comment by zmrow** [comment]
Will also need to move these files around before merge since I didn't get it in before things got renamed. :)

**Comment by mirceal** [comment]
I think we need to check what configure_networking does.
In case that the network does not come up (ie cable not connected) it might get stuck in a loop attempting to bring it up and/or it might panic and reboot. If that's the case it will not work in offline mode. 

i also think that the "okay to work in offline mode" flag should be set in the cattlepi config itself so that the pi has network access at least once to be configured/download the images.

**Comment by zmrow** [comment]
I'll take a look at configure_networking.  I have a feeling that it does the right thing.

As far as the config flag is concerned, it probably isn't necessary.  If the Pi doesn't have images and doesn't have network - 'offline mode' won't really work regardless.  That's the way that it's currently set up.  All that is to say that the Pi needs to have network at least once to get the images and then can work in offline mode if there's no connectivity with the API.  This seems like a sane default without requiring user interaction or flags being set.

**Comment by zmrow** [comment]
I don't see anything in `configure_networking that suggests it will get stuck in a loop. [Source here](https://salsa.debian.org/kernel-team/initramfs-tools/blob/master/scripts/functions)

It appears that it will just fail, which should be fine.  That being said, I'll ensure that this goes through some good testing.

**Comment by zmrow** [comment]
Agreed, let's add that in a separate PR.

I'll give this some testing and merge it if you're good with the current implementation.

**Comment by zmrow** [comment]
Updated to resolve conflicts with master. 

Pending testing, this is ready to be merged unless there are concerns with implementation.

**Comment by mirceal** [comment]
did you manage to validate this? 
thanks

**Comment by zmrow** [comment]
Found a few issues in my testing, working on those now.

**Comment by zmrow** [comment]
Fixed the few small issues I came across and tested with:
```
No rootfs == only initramfs on the SD card
-----
No rootfs | No network
No rootfs | Network
Rootfs      | No Network
Rootfs      | Network
```
The feature works as designed, and I'll open 2 issues for some related but outstanding things I've run into.

**Pull request merged**
